name: Test Reusable Workflow

# Manual test for the comment revalidation reusable workflow
# This validates the workflow can be called correctly by other repositories

on:
  workflow_dispatch:
    inputs:
      pr-number:
        description: 'PR number to test against'
        required: true
        type: number
      test-comment:
        description: 'Simulated comment text'
        required: false
        type: string
        default: '@usable This is a test of the reusable workflow. Please validate the PR with this override context.'

jobs:
  test-reusable:
    name: Test Reusable Workflow Call
    uses: ./.github/workflows/comment-revalidation.yml
    with:
      workspace-id: '60c10ca2-4115-4c1a-b6d7-04ac39fd3938'
      prompt-file: 'templates/basic-validation.md'
      gemini-model: 'gemini-2.5-flash'
      comment-title: '🧪 Reusable Workflow Test'
      fail-on-critical: false
    secrets:
      GEMINI_SERVICE_ACCOUNT_KEY: ${{ secrets.GEMINI_SERVICE_ACCOUNT_KEY }}
      USABLE_API_TOKEN: ${{ secrets.USABLE_API_TOKEN }}
    permissions:
      contents: read
      pull-requests: write

  report-results:
    name: Report Test Results
    runs-on: ubuntu-latest
    needs: test-reusable
    if: always()
    steps:
      - name: Check Results
        run: |
          echo "::notice::Reusable workflow test completed"
          echo "Status: ${{ needs.test-reusable.result }}"
          
          if [ "${{ needs.test-reusable.result }}" = "success" ]; then
            echo "✅ Reusable workflow executed successfully"
            echo "The workflow can be called from other repositories"
          else
            echo "::warning::Reusable workflow test did not complete successfully"
            echo "Result: ${{ needs.test-reusable.result }}"
          fi
      
      - name: Test Summary
        run: |
          cat << EOF
          ## Reusable Workflow Test Summary
          
          **Purpose**: Verify the comment-revalidation.yml reusable workflow can be called from other repositories
          
          **Test Configuration**:
          - Workspace ID: 60c10ca2-4115-4c1a-b6d7-04ac39fd3938
          - Prompt File: templates/basic-validation.md
          - Model: gemini-2.5-flash
          - Comment Title: 🧪 Reusable Workflow Test
          
          **Result**: ${{ needs.test-reusable.result }}
          
          **Next Steps**:
          - If successful: Reusable workflow is ready for users
          - If failed: Check workflow logs for errors
          
          **How Users Will Call It**:
          \`\`\`yaml
          uses: flowcore/usable-pr-validator/.github/workflows/comment-revalidation.yml@v1
          with:
            workspace-id: 'their-workspace-uuid'
          secrets:
            GEMINI_SERVICE_ACCOUNT_KEY: \${{ secrets.GEMINI_SERVICE_ACCOUNT_KEY }}
            USABLE_API_TOKEN: \${{ secrets.USABLE_API_TOKEN }}
          \`\`\`
          EOF

